# Generated by Django 5.0.4 on 2024-04-20 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Curso', '0002_alter_curso_nombre'),
        ('Elemento', '0002_alter_elemento_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdCurso', models.ForeignKey(db_column='IdCurso', on_delete=django.db.models.deletion.CASCADE, to='Curso.curso')),
                ('IdElemento', models.ForeignKey(db_column='IdElemento', on_delete=django.db.models.deletion.CASCADE, to='Elemento.elemento')),
            ],
        ),
    ]
