# Generated by Django 5.0.4 on 2024-04-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloque', '0002_alter_bloque_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloque',
            name='Nombre',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
