# Generated by Django 5.0.4 on 2024-04-20 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bloque', '0002_alter_bloque_nombre'),
        ('Estudiante', '0002_alter_estudiante_apellido_alter_estudiante_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteBloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdBloque', models.ForeignKey(db_column='IdBloque', on_delete=django.db.models.deletion.CASCADE, to='Bloque.bloque')),
                ('IdEstudiante', models.ForeignKey(db_column='IdEstudiante', on_delete=django.db.models.deletion.CASCADE, to='Estudiante.estudiante')),
            ],
        ),
    ]
