# Generated by Django 5.0.4 on 2024-04-20 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CursoElemento', '0001_initial'),
        ('EstudianteBloque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nota', models.DecimalField(decimal_places=1, max_digits=3)),
                ('IdCursoElemento', models.ForeignKey(db_column='IdCursoElemento', on_delete=django.db.models.deletion.CASCADE, to='CursoElemento.cursoelemento')),
                ('IdEstudianteBloque', models.ForeignKey(db_column='IdEstudianteBloque', on_delete=django.db.models.deletion.CASCADE, to='EstudianteBloque.estudiantebloque')),
            ],
        ),
    ]
