# Generated by Django 5.0.4 on 2024-04-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elemento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='Nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
