# Generated by Django 5.0.4 on 2024-04-20 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EstudianteBloque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroCuota', models.CharField(max_length=2)),
                ('Monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Estado', models.BooleanField(default=False)),
                ('IdEstudianteBloque', models.ForeignKey(db_column='IdEstudianteBloque', on_delete=django.db.models.deletion.CASCADE, to='EstudianteBloque.estudiantebloque')),
            ],
        ),
    ]
