# Generated by Django 5.0.4 on 2024-04-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(verbose_name=50)),
                ('Apellido', models.CharField(verbose_name=50)),
                ('DNI', models.CharField(unique=True, verbose_name=8)),
                ('Telefono', models.CharField(verbose_name=9)),
                ('Correo', models.CharField(verbose_name=50)),
                ('Contraseña', models.CharField()),
                ('FechaContratacion', models.DateField()),
            ],
        ),
    ]
