# Generated by Django 5.0.4 on 2024-04-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0002_alter_empleado_apellido_alter_empleado_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='DNI',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
