# Generated by Django 5.0.4 on 2024-04-20 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BloqueCurso', '0001_initial'),
        ('Empleado', '0003_alter_empleado_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueCursoProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdBloqueCurso', models.ForeignKey(db_column='IdBloqueCurso', on_delete=django.db.models.deletion.CASCADE, to='BloqueCurso.bloquecurso')),
                ('IdProfesor', models.ForeignKey(db_column='IdProfesor', on_delete=django.db.models.deletion.CASCADE, to='Empleado.empleado')),
            ],
        ),
    ]
